num_bases: 4
emb_dim: 100
num_layers: 5
dropout: 0.0
JK: "last"
lr: 0.0001
l2: 0
num_epochs: 50
batch_size: 128
eval_batch_size: 128
num_workers: 4
seed: 1
data_path:
offline_log: False
test_rep: 1
exp_name: "time_cal"
train_sample_size: -1
eval_sample_size: -1
rwpe:
task_names:
  - arxiv
llm_name: "ST"
llm_b_size: 1
val_interval: 1
